services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/zeus-docker
      NODE_ENV: docker
      SOCCER_PL_2024_SLACK_CHANNEL_ID: ${SOCCER_PL_2024_SLACK_CHANNEL_ID}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SUBSCRIBE_USERS_SLACK_CHANNEL_ID: ${SUBSCRIBE_USERS_SLACK_CHANNEL_ID}
      UNSUBSCRIBE_USERS_SLACK_CHANNEL_ID: ${UNSUBSCRIBE_USERS_SLACK_CHANNEL_ID}
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: zeus-db
    environment:
      POSTGRES_DB: zeus-docker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5426:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d zeus-docker']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
     - my-network

volumes:
  postgres_data:

networks:
  my-network:
    name: my-network
