services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/mike-docker
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  my-network:
    external: true
    name: my-network
