services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/mike-docker
      EMAILJS_SERVICE_ID: ${EMAILJS_SERVICE_ID}
      EMAILJS_TEMPLATE_ID: ${EMAILJS_TEMPLATE_ID}
      EMAILJS_PUBLIC_KEY: ${EMAILJS_PUBLIC_KEY}
      EMAILJS_PRIVATE_KEY: ${EMAILJS_PRIVATE_KEY}
      NODE_ENV: docker
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      SOCCER_PL_2024_SLACK_CHANNEL_ID: ${SOCCER_PL_2024_SLACK_CHANNEL_ID}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SUBSCRIBE_USERS_SLACK_CHANNEL_ID: ${SUBSCRIBE_USERS_SLACK_CHANNEL_ID}
      UNSUBSCRIBE_USERS_SLACK_CHANNEL_ID: ${UNSUBSCRIBE_USERS_SLACK_CHANNEL_ID}
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  my-network:
    external: true
    name: my-network
